### ISSUE TITLE
QRFcapacity::get_flowines in qrf_writeup.Rmd

### ISSUE THREAD

**Issue by mackerman44** [KevinSee/MRA_QRF#1]
Wasn't totally sure whether to post this in [QRFcapacity](https://github.com/KevinSee/QRFcapacity) or here.

Currently can't knit the qrf_writeup.Rmd doc due to issue in the wtsd_maps code chunk. The current lines 383-386:

```   
strm_lines = QRFcapacity::get_flowlines(stream_order = 2,
                                            wtsd_polygon = wtsd_bndry) %>%
      st_transform(st_crs(x)) %>%
      filter(grepl(unique(x$HUC_8), reachcode))
```
uses the `QRFcapacity::get_flowlines` function references a website [http://cida.usgs.gov/nwc/geoserver/nhdplus/ows](http://cida.usgs.gov/nwc/geoserver/nhdplus/ows), which unfortunately, no longer exists. That website has since been replaced by [http://waterdata.usgs.gov](http://waterdata.usgs.gov).

In the long-term, we should update the `get_flowlines` function to grab that data from the [http://waterdata.usgs.gov](http://waterdata.usgs.gov), which will require finding where the appropriate data is stored on that website.

In the short-term, we could update those lines 383-386 in get_writeup.Rmd to instead grab the stream layers for the Lemhi, Pahsimeroi, and Upper Salmon from elsewhere.

**Comment by KevinSee** [comment]
I updated the `get_flowlines()` function in QRFcapacity. It works now.
